apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: siem
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PlatformForgeTechnologies/forge-siem.git
    targetRevision: HEAD
    path: k8s-apps/siem
  destination:
    server: https://kubernetes.default.svc
    namespace: siem
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
