apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.secretNames.runtime }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: {{ .Values.global.secretNames.runtime }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.global.redis.usernameSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.redis.usernameSecretKey }}
    - secretKey: {{ .Values.global.redis.passwordSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.redis.passwordSecretKey }}
    - secretKey: {{ .Values.global.postgres.dsnSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.postgres.dsnSecretKey }}
    - secretKey: {{ .Values.global.rabbitmq.urlSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.rabbitmq.urlSecretKey }}
    - secretKey: {{ .Values.global.response.hmacSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.response.hmacSecretKey }}
    - secretKey: {{ .Values.global.api.authTokenSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.api.authTokenSecretKey }}
    - secretKey: {{ .Values.global.loki.pushURLSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.loki.pushURLSecretKey }}
    - secretKey: {{ .Values.global.loki.tenantIDSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.loki.tenantIDSecretKey }}
    - secretKey: {{ .Values.global.loki.usernameSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.loki.usernameSecretKey }}
    - secretKey: {{ .Values.global.loki.passwordSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.loki.passwordSecretKey }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.secretNames.tls }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: {{ .Values.global.secretNames.tls }}
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: ca.crt
    - secretKey: tls.crt
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: tls.key
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.secretNames.opensearch }}
  namespace: {{ .Values.namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secrets-manager
  target:
    name: {{ .Values.global.secretNames.opensearch }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.global.opensearch.urlSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.opensearch.urlSecretKey }}
    - secretKey: {{ .Values.global.opensearch.usernameSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.opensearch.usernameSecretKey }}
    - secretKey: {{ .Values.global.opensearch.passwordSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.opensearch.passwordSecretKey }}
    - secretKey: {{ .Values.global.opensearch.adminPasswordSecretKey }}
      remoteRef:
        key: {{ .Values.global.secretsManagerPath }}
        property: {{ .Values.global.opensearch.adminPasswordSecretKey }}
