apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: siem-decoder
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: siem-decoder
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
        metricName: siem_redis_stream_raw_lag
        query: sum(siem_redis_stream_raw_lag)
        threshold: "100"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: siem-rules-engine
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    name: siem-rules-engine
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
        metricName: siem_redis_stream_decoded_lag
        query: sum(siem_redis_stream_decoded_lag)
        threshold: "100"
