apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: siem-opensearch
  namespace: {{ .Values.namespace }}
spec:
  serviceName: siem-opensearch
  replicas: {{ .Values.opensearch.replicas }}
  selector:
    matchLabels:
      app: siem-opensearch
  template:
    metadata:
      labels:
        app: siem-opensearch
    spec:
      containers:
        - name: opensearch
          image: {{ .Values.images.opensearch }}
          env:
            - name: discovery.type
              value: single-node
{{- if .Values.opensearch.securityEnabled }}
            - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretNames.opensearch }}
                  key: {{ .Values.global.opensearch.adminPasswordSecretKey }}
{{- end }}
{{- if not .Values.opensearch.securityEnabled }}
            - name: DISABLE_INSTALL_DEMO_CONFIG
              value: "true"
            - name: DISABLE_SECURITY_PLUGIN
              value: "true"
{{- end }}
          ports:
            - containerPort: 9200
              name: http
          volumeMounts:
            - name: data
              mountPath: /usr/share/opensearch/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: {{ .Values.opensearch.storageSize }}
---
apiVersion: v1
kind: Service
metadata:
  name: siem-opensearch
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: siem-opensearch
  ports:
    - port: 9200
      targetPort: http
      name: http
