apiVersion: apps/v1
kind: Deployment
metadata:
  name: siem-raw-archiver
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.rawArchiver.replicas }}
  selector:
    matchLabels:
      app: siem-raw-archiver
  template:
    metadata:
      labels:
        app: siem-raw-archiver
    spec:
      containers:
        - name: raw-archiver
          image: {{ .Values.images.rawArchiver }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: REDIS_ADDRESS
              value: {{ printf "%s:%v" .Values.global.redis.host .Values.global.redis.port | quote }}
            - name: REDIS_DB
              value: {{ .Values.global.redis.db | quote }}
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretNames.runtime }}
                  key: {{ .Values.global.redis.usernameSecretKey }}
                  optional: true
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretNames.runtime }}
                  key: {{ .Values.global.redis.passwordSecretKey }}
                  optional: true
            - name: OPENSEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretNames.opensearch }}
                  key: {{ .Values.global.opensearch.urlSecretKey }}
            - name: OPENSEARCH_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretNames.opensearch }}
                  key: {{ .Values.global.opensearch.usernameSecretKey }}
                  optional: true
            - name: OPENSEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.global.secretNames.opensearch }}
                  key: {{ .Values.global.opensearch.passwordSecretKey }}
                  optional: true
          ports:
            - containerPort: 9090
              name: metrics
          readinessProbe:
            httpGet:
              path: /healthz
              port: metrics
          livenessProbe:
            httpGet:
              path: /healthz
              port: metrics
---
apiVersion: v1
kind: Service
metadata:
  name: siem-raw-archiver
  namespace: {{ .Values.namespace }}
  labels:
    app: siem-raw-archiver
    siem.metrics: "true"
spec:
  selector:
    app: siem-raw-archiver
  ports:
    - port: 9090
      targetPort: metrics
      name: metrics
